version: '3.4'

services:
  jenkins:
    container_name: jenkins
    build: "jenkins/"
    ports:
      - "18080:8080"
    environment:
      - JAVA_OPTS:-Djava.awt.headless=true
    volumes:
      - jenkins_home:/var/jenkins_home
      
volumes:
  jenkins_home:
 
