version: '3.7'

services:

   jenkins-master:
      build: 
         context: ./master
         dockerfile: Dockerfile.jk-master-single-worker-multiple
      container_name: jenkins-master
      volumes:
         - ./jk-master-single-worker-multiple-vol/master/home:/var/jenkins_home
         - ./master/casc-config-jk-master-single-worker-multiple/casc_configs:/var/jenkins_conf/casc_configs
         - ./master/keys:/var/jenkins_home/.ssh
         - /var/run/docker.sock:/var/run/docker.sock:ro
      ports:
         # Port UI
         - "8080:8080"
         # Port agents TCP Connection 
         - "50000:50000"
      environment:
         JENKINS_ADMIN_ID: admin
         JENKINS_ADMIN_PASSWORD: password
         CASC_JENKINS_CONFIG: /var/jenkins_conf/casc_configs
      secrets:
         - adminsecretpw
      networks:
         - jenkins-net
      depends_on:
         - jenkins-worker-1
         - jenkins-worker-2
      healthcheck:
         test: ["CMD-SHELL", "curl -s  http://127.0.0.1:8080 -o /dev/null || exit 1"]
         interval: 30s
         timeout: 5s
         retries: 3

   jenkins-worker-1:
      build:
         context: ./worker/jenkins-worker
         dockerfile: Dockerfile.ssh.agent
      container_name: jenkins-worker-1
      environment:
         JAVA_OPTS: "-Dfile.encoding=UTF-8"
      volumes:
         - ./jk-master-single-worker-multiple-vol/worker-1/home:/var/jenkins_home
         - ./master/keys:/var/jenkins_home/.ssh
         #- /var/run/docker.sock:/var/run/docker.sock
      networks:
         - jenkins-net
      healthcheck:
         test: ["CMD-SHELL", "nc -v -w 10 -z 127.0.0.1 22"]
         interval: 10s
         timeout: 5s
         retries: 3

   jenkins-worker-2:
      build:
         context: ./worker/jenkins-worker
         dockerfile: Dockerfile.ssh.agent
      container_name: jenkins-worker-2
      environment:
         JAVA_OPTS: "-Dfile.encoding=UTF-8"
      volumes:
         - ./jk-master-single-worker-multiple-vol/worker-2/home:/var/jenkins_home
         - ./master/keys:/var/jenkins_home/.ssh
         #- /var/run/docker.sock:/var/run/docker.sock
      networks:
         - jenkins-net
      healthcheck:
         test: ["CMD-SHELL", "nc -v -w 10 -z 127.0.0.1 22"]
         interval: 10s
         timeout: 5s
         retries: 3

secrets:
   adminsecretpw:
      file: ./jenkins-casc/secrets/admin.txt

networks:
   jenkins-net:
      # external: true
