version: "3.7"
services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    ports:
      - "8082:8082"
      - "8081:8081"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - nexus-data:/nexus-data
volumes:
  nexus-data: