version: '3.7'

services:

   postgres-test:
      build: ./postgres-11
      container_name: postgres-test
      environment:
         POSTGRES_USER: test
         POSTGRES_PASSWORD: test
         POSTGRES_DB: acme
      ports:
         - 5432:5432
