version: '3'
services:
  
  zookeeper-1:
    image: zookeeper:3.4.9
    hostname: zookeeper-1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zookeeper-1:2888:3888
        ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - ./zk-single-kafka-single-full-stack/zookeeper-1/data:/data
      - ./zk-single-kafka-single-full-stack/zookeeper-1/datalog:/datalog
  
  kafka-1:
    image: confluentinc/cp-kafka:5.4.0
    hostname: kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181"
      KAFKA_BROKER_ID: 1
      # KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./zk-single-kafka-single-full-stack/kafka-1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper-1

  zoonavigator:
    image: elkozmon/zoonavigator:0.8.0
    ports:
      - "8000:8000"
    environment:
      HTTP_PORT: 8000
      AUTO_CONNECT_CONNECTION_STRING: "zookeeper-1:2181"
    depends_on:
      - zookeeper-1

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:5.4.1
    hostname: kafka-schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-1:19092
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - zookeeper-1
      - kafka-1

