version: '3.4'

networks:
  ci-stack-net:
    driver: bridge

services:

  sonarqubedb:
    image: postgres:9.6
    restart: always
    ports:
     - "15432:5432"
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
    networks:
      - ci-stack-net
    volumes:
      - sonarqube_postgresql:/var/lib/postgresql
      - sonarqube_postgresql_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube
    restart: always
    ports:
     - "19000:9000"
     - "19092:9092"
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqubedb:5432/sonar
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar
    depends_on:
      - sonarqubedb
    networks:
      - ci-stack-net
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  nexus:
    build: ./docker-nexus3
    restart: always
    ports:
      - "18081:8081"
    networks:
      - ci-stack-net
    volumes:
      - nexus-data:/nexus-data    

volumes:
  sonarqube_postgresql:
  sonarqube_postgresql_data:   
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  nexus-data:
  jenkins-data:    
    
    
    